### ISSUE TITLE
DVD IFO files no longer show correct language/runtime information

### ISSUE THREAD

**Issue by vevv** [MediaArea/MediaInfo#760]
This appears to be a change in 23.07. Previously, IFO could be relied upon for language and runtime, but now that's no longer the case, breaking existing tooling assuming that. In older versions, IFO&VOB provided all necessary information, but mediainfo of the IFO is missing the exact same things as mediainfo of the VOB.

<details>
  <summary>23.07</summary>
 
IFO:
```
General
Complete name : VTS_01_0.IFO
Format : DVD Video
File size : 1.00 GiB
Duration : 15 min 2 s
Overall bit rate mode : Variable
Overall bit rate : 9 515 kb/s
Frame rate : 29.970 FPS

Video
ID : 224 (0xE0)
Format : MPEG Video
Format version : Version 2
Format profile : Main@Main
Format settings : CustomMatrix / BVOP
Format settings, BVOP : Yes
Format settings, Matrix : Custom
Format settings, GOP : M=3, N=15
Format settings, picture structure : Frame
Duration : 15 min 2 s / 22 min 22 s
Bit rate mode : Variable
Bit rate : 8 749 kb/s
Maximum bit rate : 8 000 kb/s
Width : 720 pixels
Height : 480 pixels
Display aspect ratio : 16:9
Frame rate : 29.970 (30000/1001) FPS
Standard : NTSC
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Interlaced
Scan order : Top Field First
Compression mode : Lossy
Bits/(Pixel*Frame) : 0.845
Time code of first frame : 02:10:58:15
Time code source : Group of pictures header
GOP, Open/Closed : Closed
Stream size : 942 MiB (92%)
intra_dc_precision : 10
Source : VTS_01_1.VOB

Audio #1
ID : 189 (0xBD)-128 (0x80)
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Muxing mode : DVD-Video
Duration : 15 min 2 s / 22 min 22 s
Bit rate mode : Constant
Bit rate : 384 kb/s
Channel(s) : 6 channels
Channel layout : L R C LFE Ls Rs
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 41.3 MiB (4%)
Service kind : Complete Main
bsid : 8
Dialog Normalization : -27
Dialog Normalization : -27 dB
compr : -5.49
compr : -5.49 dB
acmod : 7
lfeon : 1
dialnorm_Average : -27
dialnorm_Average : -27 dB
dialnorm_Minimum : -27
dialnorm_Minimum : -27 dB
dialnorm_Maximum : -27
dialnorm_Maximum : -27 dB
dialnorm_Count : 467
compr_Average : 0.07
compr_Average : 0.07 dB
compr_Minimum : -6.88
compr_Minimum : -6.88 dB
compr_Maximum : 5.46
compr_Maximum : 5.46 dB
compr_Count : 459
dynrng_Average : 15.85
dynrng_Average : 15.85 dB
dynrng_Minimum : -22.36
dynrng_Minimum : -22.36 dB
dynrng_Maximum : 23.94
dynrng_Maximum : 23.94 dB
dynrng_Count : 467
Source : VTS_01_1.VOB

Audio #2
ID : 189 (0xBD)-129 (0x81)
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Muxing mode : DVD-Video
Duration : 15 min 2 s / 22 min 22 s
Bit rate mode : Constant
Bit rate : 192 kb/s
Channel(s) : 2 channels
Channel layout : L R
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 20.7 MiB (2%)
Service kind : Complete Main
bsid : 8
Dialog Normalization : -27
Dialog Normalization : -27 dB
compr : 3.52
compr : 3.52 dB
dynrng : -18.20
dynrng : -18.20 dB
dsurmod : 0
acmod : 2
lfeon : 0
dialnorm_Average : -27
dialnorm_Average : -27 dB
dialnorm_Minimum : -27
dialnorm_Minimum : -27 dB
dialnorm_Maximum : -27
dialnorm_Maximum : -27 dB
dialnorm_Count : 469
compr_Average : 3.29
compr_Average : 3.29 dB
compr_Minimum : -1.16
compr_Minimum : -1.16 dB
compr_Maximum : 5.74
compr_Maximum : 5.74 dB
compr_Count : 367
dynrng_Average : 10.30
dynrng_Average : 10.30 dB
dynrng_Minimum : -20.74
dynrng_Minimum : -20.74 dB
dynrng_Maximum : 22.44
dynrng_Maximum : 22.44 dB
dynrng_Count : 469
Source : VTS_01_1.VOB

Text #1
ID : 189 (0xBD)-32 (0x20)
Format : RLE
Format/Info : Run-length encoding
Muxing mode : DVD-Video
Duration : 15 min 0 s / 22 min 22 s
Delay relative to video : 200 ms
Source : VTS_01_1.VOB

Text #2
ID : 189 (0xBD)-33 (0x21)
Format : RLE
Format/Info : Run-length encoding
Muxing mode : DVD-Video
Duration : 15 min 0 s / 22 min 22 s
Delay relative to video : 200 ms
Source : VTS_01_1.VOB

Text #3
ID : 189 (0xBD)-34 (0x22)
Format : RLE
Format/Info : Run-length encoding
Muxing mode : DVD-Video
Duration : 15 min 0 s / 22 min 22 s
Delay relative to video : 200 ms
Source : VTS_01_1.VOB

Menu #1
Duration : 22 min 22 s
00:00:00.000 : Chapter 1
00:05:26.000 : Chapter 2
00:11:49.000 : Chapter 3
00:20:05.000 : Chapter 4
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0
Source : VTS_01_1.VOB

Menu #2
Duration : 19 min 25 s
00:00:00.000 : Chapter 1
00:04:42.500 : Chapter 2
00:10:29.500 : Chapter 3
00:18:25.500 : Chapter 4
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0
Source : VTS_01_1.VOB

Menu #3
Duration : 15 min 4 s
00:00:00.000 : Chapter 1
00:05:12.500 : Chapter 2
00:10:10.500 : Chapter 3
00:13:33.500 : Chapter 4
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0
Source : VTS_01_1.VOB

Menu #4
Duration : 14 min 5 s
00:00:00.000 : Chapter 1
00:01:43.500 : Chapter 2
00:06:21.500 : Chapter 3
00:12:11.500 : Chapter 4
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0
Source : VTS_01_1.VOB

Menu #5
Duration : 27 min 57 s
00:00:00.000 : Chapter 1
00:00:05.640 : Chapter 2
00:00:42.640 : Chapter 3
00:01:08.640 : Chapter 4
00:01:41.640 : Chapter 5
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0
Source : VTS_01_1.VOB
```

VOB:
```
General
Complete name : VTS_01_1.VOB
CompleteName_Last : VTS_01_5.VOB
Format : MPEG-PS
File size : 4.13 GiB
Duration : 27 min 58 s
Overall bit rate mode : Variable
Overall bit rate : 21.1 Mb/s
Frame rate : 29.970 FPS

Video
ID : 224 (0xE0)
Format : MPEG Video
Format version : Version 2
Format profile : Main@Main
Format settings : CustomMatrix / BVOP
Format settings, BVOP : Yes
Format settings, Matrix : Custom
Format settings, GOP : M=3, N=15
Format settings, picture structure : Frame
Duration : 27 min 58 s
Bit rate mode : Variable
Bit rate : 20.1 Mb/s
Maximum bit rate : 8 000 kb/s
Width : 720 pixels
Height : 480 pixels
Display aspect ratio : 16:9
Frame rate : 29.970 (30000/1001) FPS
Standard : NTSC
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Interlaced
Scan order : Top Field First
Compression mode : Lossy
Bits/(Pixel*Frame) : 1.944
Time code of first frame : 02:10:58:15
Time code source : Group of pictures header
GOP, Open/Closed : Closed
Stream size : 3.93 GiB (95%)

Audio #1
ID : 189 (0xBD)-128 (0x80)
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Muxing mode : DVD-Video
Duration : 27 min 58 s
Bit rate mode : Constant
Bit rate : 384 kb/s
Channel(s) : 6 channels
Channel layout : L R C LFE Ls Rs
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 76.8 MiB (2%)
Service kind : Complete Main

Audio #2
ID : 189 (0xBD)-129 (0x81)
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Muxing mode : DVD-Video
Duration : 27 min 58 s
Bit rate mode : Constant
Bit rate : 192 kb/s
Channel(s) : 2 channels
Channel layout : L R
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 38.4 MiB (1%)
Service kind : Complete Main

Text #1
ID : 189 (0xBD)-32 (0x20)
Format : RLE
Format/Info : Run-length encoding
Muxing mode : DVD-Video
Delay relative to video : 200 ms

Text #2
ID : 189 (0xBD)-33 (0x21)
Format : RLE
Format/Info : Run-length encoding
Muxing mode : DVD-Video
Delay relative to video : 200 ms

Text #3
ID : 189 (0xBD)-34 (0x22)
Format : RLE
Format/Info : Run-length encoding
Muxing mode : DVD-Video
Delay relative to video : 200 ms

Menu
Format : DVD-Video
```
  
</details>

<details>
  <summary>23.06</summary>

IFO:  
```
General
Complete name : VTS_01_0.IFO
Format : DVD Video
Format profile : Program
File size : 76.0 KiB
Duration : 27 min 57 s
Overall bit rate mode : Variable
Overall bit rate : 371 b/s
Frame rate : 29.970 FPS

Video
ID : 224 (0xE0)
Format : MPEG Video
Format version : Version 2
Duration : 27 min 57 s
Bit rate mode : Variable
Width : 720 pixels
Height : 480 pixels
Display aspect ratio : 16:9
Frame rate : 29.970 (29970/1000) FPS
Standard : NTSC
Compression mode : Lossy

Audio #1
ID : 128 (0x80)
Format : AC-3
Format/Info : Audio Coding 3
Duration : 27 min 57 s
Channel(s) : 6 channels
Sampling rate : 48.0 kHz
Compression mode : Lossy
Language : Korean

Audio #2
ID : 129 (0x81)
Format : AC-3
Format/Info : Audio Coding 3
Duration : 27 min 57 s
Channel(s) : 2 channels
Sampling rate : 48.0 kHz
Compression mode : Lossy
Language : Chinese

Text #1
ID : 32 (0x20)
Format : RLE
Format/Info : Run-length encoding
Bit depth : 2 bits
Language : Chinese

Text #2
ID : 33 (0x21)
Format : RLE
Format/Info : Run-length encoding
Bit depth : 2 bits
Language : Chinese

Text #3
ID : 34 (0x22)
Format : RLE
Format/Info : Run-length encoding
Bit depth : 2 bits
Language : English

Menu #1
Duration : 12 min 4 s
00:00:00.000 : Chapter 1
00:04:19.500 : Chapter 2
00:10:51.500 : Chapter 3
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0

Menu #2
Duration : 22 min 22 s
00:00:00.000 : Chapter 1
00:05:26.000 : Chapter 2
00:11:49.000 : Chapter 3
00:20:05.000 : Chapter 4
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0

Menu #3
Duration : 19 min 25 s
00:00:00.000 : Chapter 1
00:04:42.500 : Chapter 2
00:10:29.500 : Chapter 3
00:18:25.500 : Chapter 4
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0

Menu #4
Duration : 15 min 4 s
00:00:00.000 : Chapter 1
00:05:12.500 : Chapter 2
00:10:10.500 : Chapter 3
00:13:33.500 : Chapter 4
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0

Menu #5
Duration : 14 min 5 s
00:00:00.000 : Chapter 1
00:01:43.500 : Chapter 2
00:06:21.500 : Chapter 3
00:12:11.500 : Chapter 4
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0

Menu #6
Duration : 27 min 57 s
00:00:00.000 : Chapter 1
00:00:05.640 : Chapter 2
00:00:42.640 : Chapter 3
00:01:08.640 : Chapter 4
00:01:41.640 : Chapter 5
List (Audio) : 0 / 1
List (Subtitles 4/3) : 0 / 0 / 0
List (Subtitles Wide) : 0 / 1 / 2
List (Subtitles Letterbox) : 0 / 1 / 2
List (Subtitles Pan&Scan) : 0 / 0 / 0

Menu #7
```

VOB:
```
General
Complete name : VTS_01_1.VOB
Format : MPEG-PS
File size : 1 024 MiB
Duration : 15 min 2 s
Overall bit rate mode : Variable
Overall bit rate : 9 515 kb/s
Frame rate : 29.970 FPS

Video
ID : 224 (0xE0)
Format : MPEG Video
Format version : Version 2
Format profile : Main@Main
Format settings : CustomMatrix / BVOP
Format settings, BVOP : Yes
Format settings, Matrix : Custom
Format settings, GOP : M=3, N=15
Format settings, picture structure : Frame
Duration : 15 min 2 s
Bit rate mode : Variable
Bit rate : 8 749 kb/s
Maximum bit rate : 8 000 kb/s
Width : 720 pixels
Height : 480 pixels
Display aspect ratio : 16:9
Frame rate : 29.970 (30000/1001) FPS
Standard : NTSC
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Interlaced
Scan order : Top Field First
Compression mode : Lossy
Bits/(Pixel*Frame) : 0.845
Time code of first frame : 02:10:58:15
Time code source : Group of pictures header
GOP, Open/Closed : Closed
Stream size : 942 MiB (92%)

Audio #1
ID : 189 (0xBD)-128 (0x80)
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Muxing mode : DVD-Video
Duration : 15 min 2 s
Bit rate mode : Constant
Bit rate : 384 kb/s
Channel(s) : 6 channels
Channel layout : L R C LFE Ls Rs
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 41.3 MiB (4%)
Service kind : Complete Main

Audio #2
ID : 189 (0xBD)-129 (0x81)
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Muxing mode : DVD-Video
Duration : 15 min 2 s
Bit rate mode : Constant
Bit rate : 192 kb/s
Channel(s) : 2 channels
Channel layout : L R
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 20.7 MiB (2%)
Service kind : Complete Main

Text #1
ID : 189 (0xBD)-32 (0x20)
Format : RLE
Format/Info : Run-length encoding
Muxing mode : DVD-Video
Duration : 15 min 0 s
Delay relative to video : 200 ms

Text #2
ID : 189 (0xBD)-33 (0x21)
Format : RLE
Format/Info : Run-length encoding
Muxing mode : DVD-Video
Duration : 15 min 0 s
Delay relative to video : 200 ms

Text #3
ID : 189 (0xBD)-34 (0x22)
Format : RLE
Format/Info : Run-length encoding
Muxing mode : DVD-Video
Duration : 15 min 0 s
Delay relative to video : 200 ms

Menu
Format : DVD-Video
```
  
</details>

**Comment by JeromeMartinez** [comment]
there was a big rework on DVD IFO for a customer and in order to have a better support, especially in ISO, it may have lead to bad collateral effects.
We already fixed some stuff about duration, please test [latest dev snapshots](https://mediaarea.net/download/snapshots/binary/).
About languages, we think we have changed nothing on this side, if dev snapshots still have this issue please share an IFO (here of info@mediaarea.net if need of private sharing).

**Comment by LostRager** [comment]
This issue still remains in all newer versions from 23.07 onwards.
